---
abstract: 'Tapper - Install everything needed for a test'
author:
  - 'AMD OSRC Tapper Team, C<< <tapper at amd64.org> >>'
  - 'AMD OSRC Tapper Team <tapper@amd64.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Temp: 0
  Tapper::Test: 3.000002
  Test::Deep: 0
  Test::Fixture::DBIC::Schema: 0
  Test::MockModule: 0
  Test::More: 0
  Test::Perl::Critic: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: freebsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tapper-Installer
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Daemon::Daemonize: 0
  File::Basename: 0
  File::Path: 0
  File::ShareDir: 0
  File::Type: 0
  Hash::Merge::Simple: 0
  IPC::Open3: 0
  List::Util: 0
  Log::Log4perl: 0
  Method::Signatures: 0
  Moose: 0
  Tapper::Base: 3.000002
  Tapper::Remote: 3.000002
  YAML: 0.72
  YAML::Syck: 1.17
version: 3.000002
